services:
  postgres:
    image: postgres:15-alpine
    container_name: lab_postgres
    environment:
      POSTGRES_USER: mpl_3
      POSTGRES_PASSWORD: zmn
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mpl_3 -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lab_net

  kafka:
    image: apache/kafka:3.7.0
    container_name: lab_kafka
    ports:
      - "9092:9092"
      - "29093:29093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      CLUSTER_ID: "Q0x1c3RlcklEXzEyMzQ1Njc4OQ"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lab_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: lab_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-lab
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - kafka
    networks:
      - lab_net
    restart: unless-stopped

volumes:
  pg_data:
  kafka_data:

networks:
  lab_net:
    driver: bridge